#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.
#
# For example, it will autocomplete both on $PROJECTS, and also assume you
# want to autocomplete on your acrbi tools projects in $TOOLS.

if [ ! -z "$1" ] && [ -s "$TOOLS/$1" ]; then
  cd "$TOOLS/$1"
else
  cd "$PROJECTS/$1"
fi
