cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'ansible'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'phpunit'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'ssh-copy-id'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'weechat'
brew 'youtube-dl'
brew 'git-flow'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'sequel-pro'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
